# Generated by Django 3.1.1 on 2020-09-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200911_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(help_text='Type phone', max_length=15),
        ),
    ]
