# Generated by Django 3.1.1 on 2020-09-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_publications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publications',
            new_name='Publication',
        ),
    ]
