# Generated by Django 3.1.1 on 2020-09-17 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200912_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorMessageName', models.CharField(max_length=128)),
                ('authorMessageEmail', models.EmailField(max_length=254)),
                ('messageText', models.TextField()),
                ('messageDate', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
