# Generated by Django 3.1.1 on 2020-09-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_feedbackform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackform',
            old_name='authorMessageEmail',
            new_name='author_message_email',
        ),
        migrations.RenameField(
            model_name='feedbackform',
            old_name='authorMessageName',
            new_name='author_message_name',
        ),
        migrations.RenameField(
            model_name='feedbackform',
            old_name='messageDate',
            new_name='message_date',
        ),
        migrations.RenameField(
            model_name='feedbackform',
            old_name='messageText',
            new_name='message_text',
        ),
    ]
